version: "3"

services:
  app:
    image: larux/zovmsk:13092023
    container_name: "${COMPOSE_PROJECT_NAME}_PROJECT"
    restart: always
    ports:
      - "3000:3000"

  nginx:
    image: nginx:alpine
    container_name: "${COMPOSE_PROJECT_NAME}_NGINX"
    ports:
      - "9958:80"
    volumes:
      - ./:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    depends_on:
      - app
