version: "3"

services:
  app:
    image: ${REGISTRY}/${PROJECT}:${IMAGE_TAG}
    container_name: "${PROJECT}_APP"
    restart: always

  nginx:
    image: nginx:alpine
    container_name: "${PROJECT}_NGINX"
    ports:
      - "${PORT}:80"
    volumes:
      - ./:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    depends_on:
      - app
