version: "3"

services:
  app:
    image: larux/...:latest
    container_name: "..._PROJECT"
    restart: always

  nginx:
    image: nginx:alpine
    container_name: "..._NGINX"
    ports:
      - "...:80"
    volumes:
      - ./:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    depends_on:
      - app
